version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: django-backend-api:1.0  
    container_name: django-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./appbackend:/usr/src/app
