# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend-deployment
  labels:
    app: django-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django-backend
        image: georgeao/django-api
        ports:
        - containerPort: 8000
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  selector:
    app: django-backend
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 8000 # Container port
  type: LoadBalancer
