# Generated by Django 5.1.3 on 2024-11-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='Rating',
            new_name='rating',
        ),
    ]
