# Generated by Django 5.1.3 on 2024-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_rating_drink_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='rating',
            field=models.FloatField(),
        ),
    ]
